name: Deploy to GCP

on:
  push:
    branches:
      - develop  # main 브랜치 push될 때만

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Deploy to GCP Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_PRIVATE_KEY }}
        script: |
          cd /home/kskcmh5723
          pkill -f 'tabbit.jar' || true
          rm -f tabbit.jar
          exit
    - name: Copy Jar to Server
      uses: appleboy/scp-action@v0.1.6
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_PRIVATE_KEY }}
        source: build/libs/tabbit.jar
        target: /home/kskcmh5723

    - name: Restart Application
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.GCP_HOST }}
        username: ${{ secrets.GCP_USERNAME }}
        key: ${{ secrets.GCP_PRIVATE_KEY }}
        script: |
          cd /home/kskcmh5723
          nohup java -jar tabbit.jar > app.log 2>&1 &
