name: Deploy to GCP
run-name: Running
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Gradle
      run: ./gradlew build

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.TABBIT_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v0.2.0
      with:
        project_id: ${{ secrets.TABBIT_PROJECT }}
        install_components: 'app-engine-java'

    - name: Deploy to GCE
      run: |
        gcloud config set compute/zone ${{ secrets.TABBIT_INSTANCE_ZONE }}
        gcloud compute scp build/libs/*.jar ${TABBIT_INSTANCE}:/home/YOUR_USER --zone ${{ secrets.TABBIT_INSTANCE_ZONE }}
        gcloud compute ssh ${TABBIT_INSTANCE} --zone ${{ secrets.TABBIT_INSTANCE_ZONE }} --command "
        sudo mv /home/YOUR_USER/*.jar /home/YOUR_USER/app.jar &&
        sudo systemctl restart my-app.service
        "
